name: "test-on-push"
on: [push, pull_request]

jobs:
  # Ensure version numbers in various places match up
  ensure-same-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          pip install toml
      - name: Run check
        run: |
          python3 scripts/check_version_numbers.py


  test-tauri:
    needs: ensure-same-version
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install app dependencies and build it
      run: |
        npm install
        cd src-vue && npm install && cd ..
        npm run tauri build
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: upload build artifact
      uses: actions/upload-artifact@v2
      with:
        path: |
          src-tauri/target/release/bundle/msi/*
